### ISSUE TITLE
Not working with Authentication and Authorization plugins

### ISSUE THREAD

**Issue by marianodonal** [dereuromark/cakephp-tinyauth#117]
Hi Mark, i've been using TinyAuth for a couple of years with cake 3.x, now i'm trying to implement it with 4.x version and new Auths plugins in middleware but is not working, always get:
**Subject must be an instance of Authentication\AuthenticationServiceInterface or Authentication\AuthenticationServiceProviderInterface, App\Application given.**

This is my code in Application.php (minor code removed):

``` php
use Authentication\Middleware\AuthenticationMiddleware;
use Authorization\Middleware\AuthorizationMiddleware;
use TinyAuth\Middleware\RequestAuthorizationMiddleware;
use TinyAuth\Policy\RequestPolicy;

class Application extends BaseApplication
{

  public function bootstrap(): void
  {
    parent::bootstrap();
    $this->addPlugin('Authentication');
    $this->addPlugin('Authorization');
    $this->addPlugin('TinyAuth');
  }

  public function getAuthorizationService(ServerRequestInterface $request, ResponseInterface $response)
  {
    $map = [
      ServerRequest::class => new RequestPolicy(),
    ];
    $resolver = new MapResolver($map);
    return new AuthorizationService($resolver);
  }

  public function middleware(MiddlewareQueue $middlewareQueue): MiddlewareQueue
  {
    $config = [
      'unauthorizedHandler' => [
        'className' => 'Authorization.Redirect',
      ],
    ];

    $middlewareQueue
    ->add(new ErrorHandlerMiddleware(Configure::read('Error')))
    ->add(new AssetMiddleware([
      'cacheTime' => Configure::read('Asset.cacheTime'),
    ]))
    ->add(new RoutingMiddleware($this))
    ->add(new AuthenticationMiddleware($this))
    ->add(new AuthorizationMiddleware($this, $config))
    ->add(new RequestAuthorizationMiddleware());

    return $middlewareQueue;
  }
}
```

**Comment by dereuromark** [comment]
You are not using it as documented.
Make sure you use TinyAuth here primarily, and as the docs suggest.
There are classes in there that overwrite the plugin code
As such, you also don't have to load the other two plugins even and it should still work
See https://github.com/dereuromark/cakephp-tinyauth/blob/master/docs/AuthorizationPlugin.md etc

**Comment by dereuromark** [comment]
It is possible that the docs changed a bit during the 4.x upgrade.
Then we would have to fix it - piece by piece.
Feel free to make PRs here where something needs adjusting.

We can also set up a small demo auth app together, and see if we can figure it out.

**Comment by dereuromark** [comment]
I started https://github.com/dereuromark/auth-demo
Maybe you can make a branch with your current setup added into it?
And then we can figure out what goes wrong here.

**Comment by marianodonal** [comment]
Thanks for your quick response, I really appreciate it!

**Comment by dereuromark** [comment]
Did you have a chance to look into that demo repo and see if you can reproduce your case?
So we can try to find a fix?

**Comment by marianodonal** [comment]
Hi Mark, I copied the Application.php code into my application and everything seems to be working fine. The only difference I noticed is that RoutingMiddleware loads after Auths, could that be the issue?

**Comment by dereuromark** [comment]
Yeah, order here can be important.
Let me know if we need to fix docs or code here.

**Comment by LubosRemplik** [comment]
Could you bump version for cake4, 3.0.0 does not include changes you did in #118 and would be better than use master branch?

Thanks

**Comment by dereuromark** [comment]
Done in https://github.com/dereuromark/cakephp-tinyauth/releases/tag/3.0.1
But yeah I think there might be a bit more issues popping up. I can always merge and release more patches, though.

**Comment by dereuromark** [comment]
Anything else missing?

**Comment by gi-jones** [comment]
I had some troubles too, and noticed that in [https://github.com/dereuromark/auth-demo](url) you have commented out the line: `->add(new RequestAuthorizationMiddleware())`
Doing that in my own application solved all my problems. However the line still exists in the documentation: [https://github.com/dereuromark/cakephp-tinyauth/blob/master/docs/AuthorizationPlugin.md](url)

I'm thinking it should be removed from the docs, but am I missing something?

**Comment by dereuromark** [comment]
That repo is 4yo, and was never fully live
It would need someone to actually showcase it.

Also, the new plugins I never used, so the functionality might also still be somewhat partially working only.
I so far only use the old "single plugin" approach which works perfectly fine for me and most others.

That said: Would be great if someone fully enables the new approaches here.
